import React from "react";
import "katex/dist/katex.min.css";
import { MathJaxContext, MathJax } from "better-react-mathjax";
import { useState } from "react";

function Markdown(props) {
  const [terms, setTerms] = useState(props.terms);

  let markDownCOntent = "";

  if (props.terms.length === 26) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})+ (${terms[20].totalCredits} \\times ${terms[20].gpa})+ (${terms[21].totalCredits} \\times ${terms[21].gpa})+ (${terms[22].totalCredits} \\times ${terms[22].gpa})+ (${terms[23].totalCredits} \\times ${terms[23].gpa})+ (${terms[24].totalCredits} \\times ${terms[24].gpa})+ (${terms[25].totalCredits} \\times ${terms[25].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}+ ${terms[20].totalCredits}+ ${terms[21].totalCredits}+ ${terms[22].totalCredits}+ ${terms[23].totalCredits}+ ${terms[24].totalCredits}+ ${terms[25].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 25) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})+ (${terms[20].totalCredits} \\times ${terms[20].gpa})+ (${terms[21].totalCredits} \\times ${terms[21].gpa})+ (${terms[22].totalCredits} \\times ${terms[22].gpa})+ (${terms[23].totalCredits} \\times ${terms[23].gpa})+ (${terms[24].totalCredits} \\times ${terms[24].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}+ ${terms[20].totalCredits}+ ${terms[21].totalCredits}+ ${terms[22].totalCredits}+ ${terms[23].totalCredits}+ ${terms[24].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 24) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})+ (${terms[20].totalCredits} \\times ${terms[20].gpa})+ (${terms[21].totalCredits} \\times ${terms[21].gpa})+ (${terms[22].totalCredits} \\times ${terms[22].gpa})+ (${terms[23].totalCredits} \\times ${terms[23].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}+ ${terms[20].totalCredits}+ ${terms[21].totalCredits}+ ${terms[22].totalCredits}+ ${terms[23].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 23) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})+ (${terms[20].totalCredits} \\times ${terms[20].gpa})+ (${terms[21].totalCredits} \\times ${terms[21].gpa})+ (${terms[22].totalCredits} \\times ${terms[22].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}+ ${terms[20].totalCredits}+ ${terms[21].totalCredits}+ ${terms[22].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 22) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})+ (${terms[20].totalCredits} \\times ${terms[20].gpa})+ (${terms[21].totalCredits} \\times ${terms[21].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}+ ${terms[20].totalCredits}+ ${terms[21].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 21) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})+ (${terms[20].totalCredits} \\times ${terms[20].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}+ ${terms[20].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 20) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})+ (${terms[19].totalCredits} \\times ${terms[19].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}+ ${terms[19].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 19) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})+ (${terms[18].totalCredits} \\times ${terms[18].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}+ ${terms[18].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 18) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})+ (${terms[17].totalCredits} \\times ${terms[17].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}+ ${terms[17].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 17) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})+ (${terms[16].totalCredits} \\times ${terms[16].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}+ ${terms[16].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 16) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})+ (${terms[15].totalCredits} \\times ${terms[15].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}+ ${terms[15].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 15) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})+ (${terms[14].totalCredits} \\times ${terms[14].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}+ ${terms[14].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 14) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})+ (${terms[13].totalCredits} \\times ${terms[13].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}+ ${terms[13].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 13) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})+ (${terms[12].totalCredits} \\times ${terms[12].gpa})}
  {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}+ ${terms[12].totalCredits}} 
  = ${props.result}\\)`;
  } else if (props.terms.length === 12) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})+ (${terms[11].totalCredits} \\times ${terms[11].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}+ ${terms[11].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 11) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})+ (${terms[10].totalCredits} \\times ${terms[10].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}+ ${terms[10].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 10) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})+ (${terms[9].totalCredits} \\times ${terms[9].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}+ ${terms[9].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 9) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})+ (${terms[8].totalCredits} \\times ${terms[8].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}+ ${terms[8].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 8) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})+ (${terms[7].totalCredits} \\times ${terms[7].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}+ ${terms[7].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 7) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})+ (${terms[6].totalCredits} \\times ${terms[6].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}+ ${terms[6].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 6) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})+ (${terms[5].totalCredits} \\times ${terms[5].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}+ ${terms[5].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 5) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})+ (${terms[4].totalCredits} \\times ${terms[4].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}+ ${terms[4].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 4) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})+ (${terms[3].totalCredits} \\times ${terms[3].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}+ ${terms[3].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 3) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa}) + (${terms[2].totalCredits} \\times ${terms[2].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits} + ${terms[2].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 2) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa}) + (${terms[1].totalCredits} \\times ${terms[1].gpa})}
    {${terms[0].totalCredits} + ${terms[1].totalCredits}} 
    = ${props.result}\\)`;
  } else if (props.terms.length === 1) {
    markDownCOntent = `\\(\\frac{(${terms[0].totalCredits} \\times ${terms[0].gpa})}
    {${terms[0].totalCredits}} 
    = ${props.result}\\)`;
  }

  return (
    <div className="h-full w-full p-4 overflow-x-scroll bg-slate-800 rounded-lg md:mx-4 mb-2 text-center">
      <MathJaxContext className="text-center">
        <MathJax className="md:text-3xl text-emerald-300 text-center">
          {markDownCOntent}
        </MathJax>
      </MathJaxContext>
    </div>
  );
}

export default Markdown;
